export enum AppCodes {
  SUCCESS = 0,
  VALIDATIONFAILED = -1,
  INVALIDJWTTOKEN = -2,
  EXPIREDJWTTOKEN = -3,
  REFRESHTOKENFAIL = -4,
  SERVERERROR = -5,
  INVALIDCREDENTIALS = -6,
  NODATA = -7,
}
